language:
  - php
  - c

php:
  - 5.4
  - 5.5

env:
  - DB=mysql ENABLE_SECOND_LEVEL_CACHE=1

before_install:
 - ./tests/ci/install_prereqs.sh
 - mysql -uroot -e 'create database phalcon_orm_test charset=utf8 collate=utf8_unicode_ci;'
 - mysql -uroot phalcon_orm_test < ./tests/schemas/mysql/phalcon_test.sql

before_script:
 - git submodule --quiet update --init --recursive
 - (cd ext; export CFLAGS="-g3 -O1 -std=gnu90 -Wall"; phpize && ./configure --enable-phalcon-orm && make --silent -j4 && sudo make --silent install && phpenv config-add ../tests/ci/phalcon.ini)
 - ulimit -c unlimited || true

script:
 - phpunit -v --configuration tests/travis/$DB.travis.xml

after_failure:
 - sudo apt-get -qq install gdb
 - ./tests/ci/after_failure.sh